apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-config
data:
  init_db.sql: |
    CREATE TABLE users (
        id SERIAL PRIMARY KEY,
        username VARCHAR(50) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        domains JSONB DEFAULT '[]'
    );

