apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: monithor-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

